### ISSUE TITLE
Error Initializing VMware powercli environment

### ISSUE THREAD

**Issue by packtman** [mothe-at/VMPerf-To-Graphite-PowerShell-Script#12]
Hi,

I am kind of naive as far as Powershell is concerned. I did everything as per your installation guideline. Both Graphite and Grafana are installed on a linux server. 

The only issue I am facing is with the below error:

VERBOSE: 4/12/2017 4:59:17 PM Initializing VMware vSphere PowerCLI environment
C:\VMPerf-To-Graphite-PowerShell-Script-master\VMPerf-To-Graphite.ps1 : Error
initializing VMWare PowerCLI environment. Cannot find path to VMWare PowerCLI
in Registry. Make sure VMWare PowerCLI is installed on this host!
At line:1 char:1
+ .\VMPerf-To-Graphite.ps1 -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,VMPerf-To-Graphite.ps1

The Powershell (4.0 - administrator mode) is not able to initialize PowerCLI (6.0) 

Can you please suggest me how should I solve this issue?

Thanks.

**Comment by packtman** [comment]
Never mind. I set a new path as shown in the image.

![idirc](https://cloud.githubusercontent.com/assets/7194155/24979948/26f0a154-1fa4-11e7-91a3-df333fc4b10a.PNG)

**Comment by mothe-at** [comment]
@packtman Thank you for raising ans solving the issue by yourself! 
Strange that the Get-Module cmdlet does not deliver the path to PowerCLI in your environment.
