### ISSUE TITLE
'sendtographite' is not recognized as cmdlet, function

### ISSUE THREAD

**Issue by luciano2683** [mothe-at/VMPerf-To-Graphite-PowerShell-Script#13]
In C:\scripts\vcenter\VMPerf-To-Graphite.ps1: 480 Carácter: 10
+             sendtographite $results
+             ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (sendtographite:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

can you helpme with that? 
Thanks!

**Comment by PaulieShore** [comment]
Are you running the script from PowerShell ISE? There's a closed issue which touches on this: https://github.com/mothe-at/VMPerf-To-Graphite-PowerShell-Script/issues/5.

**Comment by luciano2683** [comment]
Thanks Paulie, it was the same error that happened on issue #5. Didnt saw "closed issues", sorry about that.
