### ISSUE TITLE
sendtographite : The term 'sendtographite' is not recognized as the name of a cmdlet, function

### ISSUE THREAD

**Issue by ghost** [mothe-at/VMPerf-To-Graphite-PowerShell-Script#5]
Trying to get this going but coming across quite a few errors. 

"checkiporhostname'
'sendtographite'

sendtographite : The term 'sendtographite' is not recognized as the name of a cmdlet, function

Any ideas ?

**Comment by mothe-at** [comment]
are you running the script from ISE? if so, can you please run it from a regular PS prompt?

**Comment by ghost** [comment]
Ah, so that got me slightly further.

Throwing this error now though;

sendtographite : The term 'sendtographite' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Users\administrator.MILL\Desktop\VMPerf-To-Graphite-PowerShell-Script-master\VMPerf-To-Graphite.ps1:460 char:10
-             sendtographite $results
-             ~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (sendtographite:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException

**Comment by PaulieShore** [comment]
Did you figure this one out? I've tried running the script in PowerCLI 6.1 R1 prompt on Windows 10 and Server 2012 R2 and receiving both of the following errors:

checkiporhostname : The term 'checkiporhostname' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Users\user\Desktop\VMPerf-To-Graphite\VMPerf-To-Graphite.ps1:287 char:2
-     checkiporhostname "Graphite" $cserver True
-     ~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (checkiporhostname:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException

sendtographite : The term 'sendtographite' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\user\Desktop\VMPerf-To-Graphite\VMPerf-To-Graphite.ps1:460 char:10
-             sendtographite $results
-             ~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (sendtographite:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException

**Comment by dirkwart** [comment]
@tomboxme @PaulieShore i got the same error. In my case it was some character encoding mismatch: i downloaded the zip file from github and extracted them on a windows machine. Executing the script threw the same errors you described. Looking at the script, i saw some broken characters:

for example Line 97: Write-EventLog –LogName Application –Source ...
--> the dash was something totally different in ISE

I opened the script in some other editor that made the character encoding right and saved the file with that editor. Executing that new file with ISE then ran without errors.

**Comment by mothe-at** [comment]
@dirkwart thanks a lot for finding this out! Have no idea why the encoding of the script got messed up on github. I fixed another bug and updated to v1.5.1. Can you please try and leave a note that Encoding is correct now?

**Comment by PaulieShore** [comment]
Awesome. I'm now able to get some stats into Graphite. However each time the script runs it's only sending metrics for 10 VM's at a time. The next time the script runs it seems to send a different set of VM's. Not sure if it's related, but I get this error as well each time the polling ends:

Exception calling "FlushInputBuffer" with "0" argument(s): "The method or operation is not implemented."
At C:\Scripts\vsphere\VMPerf-To-Graphite.ps1:521 char:9
-         $Host.UI.RawUI.FlushInputBuffer()
-         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : NotImplementedException

I just wanted to thank you for this script. I love Graphite and Grafana but I've been having such a difficult time getting the data sent to Graphite from vCenter. Thanks for helping out 💯!

**Comment by mothe-at** [comment]
@PaulieShore great that it finally works, thank you for the feedback!

Do you run the script from PowerShell ISE or a prompt? The FlushInputBuffer Error usually comes from running the script from ISE, this will not work properly. If so, please run it from a PowerShell prompt.

Just 10 VMs, hm. You could run the script with the -Verbose and the -WhatIf switches. Then noting is sent to Graphite but you will get the output what WOULD be sent. Are there all VMs or just 10?
If you can see all VMs there, it might be your Carbon configuration. There are limits on how many "creates" and "updates" per time interval are accepted by Carbon.
Please check your `carbon.conf` for "`MAX_CREATES_PER_MINUTE`" and "`MAX_UPDATES_PER_SECOND`". Remember that if you run the script for the first time(s), many thousands of creates will happen and I think the default is 2000 creates per minute. This could cause the VMs appear slowly in Grafana.

**Comment by PaulieShore** [comment]
I think you're right. It's a carbon config somewhere. After about an hour the metrics started flowing in normally (sorry, I should have updated my post). 

As for the error, you're right again. I was testing from ISE. Now I just need to pick a way to schedule the task from one of my Windows servers. Awesome :) 

You've been a great help and thank you very much for this awesome script.

I'm going to write up a full how to on how to get this implemented. I'll shoot you the link when it's published. Cheers!

**Comment by mothe-at** [comment]
@PaulieShore Cool!

Suggestion for a .cmd Script that I run every 10 Minutes from my scheduled tasks:

`@echo off`
`cd /D C:\VMPerf`
`powershell.exe .\VMPerf-To-Graphite.ps1 -server YOUR_VCENTER_SERVER -user VCENTER_USER -password VCENTER_PASS -Graphiteserver YOUR_GRAPHITE_SERVER -Iterations 1 -Group Vienna -EventLogLevel Warning -FromLastPoll VMPerf_Vienna.xml -Verbose >> VMPerf_Vienna.log 2>&1`

I poll three different locations, so I created three batch-files and three scheduled tasks. Dont forget to adapt the -FromLastPoll switch, they are also different per site I poll.
This also writes a log file (VMPerf_Vienna.log) of what is happening.

Cheers!

**Comment by dirkwart** [comment]
@mothe-at Encoding is now correct on all my machines, too - thank you!

**Comment by mothe-at** [comment]
Added a sample batch file for use with Windows Scheduled Tasks and added a comment about NOT running the script from Powershell ISE.
Thank you, guys, for your inputs!
Closing this Issue.
